"""add product catalog inventory and serial lifecycle

Revision ID: 00508f14101d
Revises: 4ee03aa57aac
Create Date: 2026-08-06 09:48:10.085391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00508f14101d'
down_revision: Union[str, Sequence[str], None] = '4ee03aa57aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units_of_measure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('decimal_places >= 0 AND decimal_places <= 6', name=op.f('ck_units_of_measure_ck_units_decimal_places_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units_of_measure')),
    sa.UniqueConstraint('name', name=op.f('uq_units_of_measure_name'))
    )
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_of_measure_code'), ['code'], unique=True)

    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_brands_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('company_id', 'code', name='uq_brands_company_code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_brands_company_name')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=False)

    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_categories_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], name=op.f('fk_product_categories_parent_id_product_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('company_id', 'code', name='uq_product_categories_company_code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_product_categories_company_name')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_parent_id'), ['parent_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('btu_capacity', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('track_serial_numbers', sa.Boolean(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('minimum_selling_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reorder_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('technical_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('minimum_selling_price <= selling_price', name=op.f('ck_products_ck_products_minimum_not_above_selling')),
    sa.CheckConstraint('minimum_selling_price >= 0', name=op.f('ck_products_ck_products_minimum_price_nonnegative')),
    sa.CheckConstraint('purchase_cost >= 0', name=op.f('ck_products_ck_products_purchase_cost_nonnegative')),
    sa.CheckConstraint('reorder_level >= 0', name=op.f('ck_products_ck_products_reorder_level_nonnegative')),
    sa.CheckConstraint('reorder_quantity >= 0', name=op.f('ck_products_ck_products_reorder_quantity_nonnegative')),
    sa.CheckConstraint('selling_price >= 0', name=op.f('ck_products_ck_products_selling_price_nonnegative')),
    sa.CheckConstraint('warranty_months >= 0', name=op.f('ck_products_ck_products_warranty_months_nonnegative')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_products_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_products_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units_of_measure.id'], name=op.f('fk_products_unit_id_units_of_measure'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_products_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('company_id', 'barcode', name='uq_products_company_barcode'),
    sa.UniqueConstraint('company_id', 'product_code', name='uq_products_company_product_code')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_model_number'), ['model_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_code'), ['product_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_type'), ['product_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_updated_by_id'), ['updated_by_id'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('warehouse_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_warehouses_branch_id_branches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('branch_id', 'code', name='uq_warehouses_branch_code')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_warehouse_type'), ['warehouse_type'], unique=False)

    op.create_table('product_serial_numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=150), nullable=False),
    sa.Column('secondary_serial_number', sa.String(length=150), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_customer_id', sa.Integer(), nullable=True),
    sa.Column('warranty_start_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_serial_numbers_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_product_serial_numbers_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_customer_id'], ['customers.id'], name=op.f('fk_product_serial_numbers_current_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_serial_numbers_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_product_serial_numbers_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_product_serial_numbers_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_serial_numbers')),
    sa.UniqueConstraint('company_id', 'serial_number', name='uq_product_serial_numbers_company_serial')
    )
    with op.batch_alter_table('product_serial_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_current_customer_id'), ['current_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_secondary_serial_number'), ['secondary_serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial_numbers_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('average_cost >= 0', name=op.f('ck_stock_items_ck_stock_items_average_cost_nonnegative')),
    sa.CheckConstraint('quantity_on_hand >= 0', name=op.f('ck_stock_items_ck_stock_items_quantity_nonnegative')),
    sa.CheckConstraint('quantity_reserved <= quantity_on_hand', name=op.f('ck_stock_items_ck_stock_items_reserved_not_above_on_hand')),
    sa.CheckConstraint('quantity_reserved >= 0', name=op.f('ck_stock_items_ck_stock_items_reserved_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_items_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_items')),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_stock_items_warehouse_product')
    )
    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_items_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serial_number_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=80), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('movement_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity != 0', name=op.f('ck_stock_movements_ck_stock_movements_quantity_nonzero')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_stock_movements_ck_stock_movements_unit_cost_nonnegative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_movements_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_movements_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_stock_movements_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['serial_number_id'], ['product_serial_numbers.id'], name=op.f('fk_stock_movements_serial_number_id_product_serial_numbers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_movements_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_date'), ['movement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_serial_number_id'), ['serial_number_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_warehouse_id'), ['warehouse_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_serial_number_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_reference_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_reference_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_date'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_company_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_branch_id'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_items_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_items_product_id'))

    op.drop_table('stock_items')
    with op.batch_alter_table('product_serial_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_status'))
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_serial_number'))
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_secondary_serial_number'))
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_current_customer_id'))
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_product_serial_numbers_company_id'))

    op.drop_table('product_serial_numbers')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_warehouse_type'))
        batch_op.drop_index(batch_op.f('ix_warehouses_is_active'))
        batch_op.drop_index(batch_op.f('ix_warehouses_code'))
        batch_op.drop_index(batch_op.f('ix_warehouses_branch_id'))

    op.drop_table('warehouses')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_products_unit_id'))
        batch_op.drop_index(batch_op.f('ix_products_product_type'))
        batch_op.drop_index(batch_op.f('ix_products_product_code'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_model_number'))
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.drop_index(batch_op.f('ix_products_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_products_company_id'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand_id'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_product_categories_name'))
        batch_op.drop_index(batch_op.f('ix_product_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_categories_company_id'))
        batch_op.drop_index(batch_op.f('ix_product_categories_code'))

    op.drop_table('product_categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_name'))
        batch_op.drop_index(batch_op.f('ix_brands_is_active'))
        batch_op.drop_index(batch_op.f('ix_brands_company_id'))
        batch_op.drop_index(batch_op.f('ix_brands_code'))

    op.drop_table('brands')
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_of_measure_code'))

    op.drop_table('units_of_measure')
    # ### end Alembic commands ###
