"""add legacy grn history tables

Revision ID: 19f9943c7b1a
Revises: a6f070650b9f
Create Date: 2026-08-16 21:03:35.556564

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "19f9943c7b1a"
down_revision: str | None = "a6f070650b9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "legacy_goods_receipts",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "supplier_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "legacy_grn_id",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "legacy_internal_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "legacy_supplier_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "legacy_grn_number",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "reference_invoice_number",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "receipt_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "net_total",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "paid_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "outstanding_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "legacy_status",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "source_system",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "source_payload",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "company_id",
            "source_system",
            "legacy_internal_id",
            name=(
                "uq_legacy_grn_"
                "company_source_internal"
            ),
        ),
        sa.UniqueConstraint(
            "company_id",
            "source_system",
            "legacy_grn_number",
            name=(
                "uq_legacy_grn_"
                "company_source_number"
            ),
        ),
    )

    op.create_index(
        "ix_legacy_goods_receipts_company_id",
        "legacy_goods_receipts",
        ["company_id"],
        unique=False,
    )

    op.create_index(
        "ix_legacy_goods_receipts_supplier_id",
        "legacy_goods_receipts",
        ["supplier_id"],
        unique=False,
    )

    op.create_index(
        "ix_legacy_grn_company_receipt_date",
        "legacy_goods_receipts",
        [
            "company_id",
            "receipt_date",
        ],
        unique=False,
    )

    op.create_index(
        "ix_legacy_grn_company_supplier",
        "legacy_goods_receipts",
        [
            "company_id",
            "supplier_id",
        ],
        unique=False,
    )

    op.create_table(
        "legacy_goods_receipt_items",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "legacy_goods_receipt_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "legacy_item_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "legacy_created_grn_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "legacy_product_code",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "legacy_product_name",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(
                precision=18,
                scale=3,
            ),
            nullable=False,
        ),
        sa.Column(
            "unit_cost",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "retail_price",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=True,
        ),
        sa.Column(
            "wholesale_price",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=True,
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "line_total",
            sa.Numeric(
                precision=18,
                scale=2,
            ),
            nullable=False,
        ),
        sa.Column(
            "temporary_stock",
            sa.Numeric(
                precision=18,
                scale=3,
            ),
            nullable=True,
        ),
        sa.Column(
            "expiry_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "expiry_status",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "legacy_type",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "serial_numbers_json",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "imeis_json",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "source_payload",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["legacy_goods_receipt_id"],
            ["legacy_goods_receipts.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "legacy_goods_receipt_id",
            "legacy_item_id",
            name=(
                "uq_legacy_grn_item_"
                "receipt_item"
            ),
        ),
    )

    op.create_index(
        "ix_legacy_goods_receipt_items_legacy_goods_receipt_id",
        "legacy_goods_receipt_items",
        ["legacy_goods_receipt_id"],
        unique=False,
    )

    op.create_index(
        "ix_legacy_grn_item_product",
        "legacy_goods_receipt_items",
        ["product_id"],
        unique=False,
    )

    op.create_index(
        "ix_legacy_grn_item_code",
        "legacy_goods_receipt_items",
        ["legacy_product_code"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_legacy_grn_item_code",
        table_name="legacy_goods_receipt_items",
    )

    op.drop_index(
        "ix_legacy_grn_item_product",
        table_name="legacy_goods_receipt_items",
    )

    op.drop_index(
        (
            "ix_legacy_goods_receipt_items_"
            "legacy_goods_receipt_id"
        ),
        table_name="legacy_goods_receipt_items",
    )

    op.drop_table(
        "legacy_goods_receipt_items"
    )

    op.drop_index(
        "ix_legacy_grn_company_supplier",
        table_name="legacy_goods_receipts",
    )

    op.drop_index(
        "ix_legacy_grn_company_receipt_date",
        table_name="legacy_goods_receipts",
    )

    op.drop_index(
        "ix_legacy_goods_receipts_supplier_id",
        table_name="legacy_goods_receipts",
    )

    op.drop_index(
        "ix_legacy_goods_receipts_company_id",
        table_name="legacy_goods_receipts",
    )

    op.drop_table(
        "legacy_goods_receipts"
    )
