"""add sales returns replacement warranty lifecycle

Revision ID: 1d0d92e814a8
Revises: eeb19d52c939
Create Date: 2026-08-09 17:06:23.543098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0d92e814a8'
down_revision: Union[str, Sequence[str], None] = 'eeb19d52c939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('refund_amount >= 0', name=op.f('ck_sales_returns_ck_sales_returns_refund_nonnegative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_sales_returns_ck_sales_returns_subtotal_nonnegative')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_sales_returns_approved_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_sales_returns_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sales_returns_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sales_returns_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_returns_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], name=op.f('fk_sales_returns_invoice_id_sales_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_sales_returns_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_returns')),
    sa.UniqueConstraint('company_id', 'return_number', name='uq_sales_returns_company_return_number')
    )
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_returns_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_resolution'), ['resolution'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_return_number'), ['return_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_return_type'), ['return_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_updated_by_id'), ['updated_by_id'], unique=False)

    op.create_table('sales_return_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_sales_return_status_history_changed_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], name=op.f('fk_sales_return_status_history_return_id_sales_returns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_return_status_history'))
    )
    with op.batch_alter_table('sales_return_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_return_status_history_changed_by_id'), ['changed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_status_history_new_status'), ['new_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_status_history_return_id'), ['return_id'], unique=False)

    op.create_table('sales_return_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('serial_number_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('destination_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('stock_movement_id', sa.Integer(), nullable=True),
    sa.Column('replacement_product_id', sa.Integer(), nullable=True),
    sa.Column('replacement_serial_number_id', sa.Integer(), nullable=True),
    sa.Column('replacement_stock_movement_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_sales_return_items_ck_sales_return_items_line_total_nonnegative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sales_return_items_ck_sales_return_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_sales_return_items_ck_sales_return_items_unit_price_nonnegative')),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], name=op.f('fk_sales_return_items_destination_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['sales_invoice_items.id'], name=op.f('fk_sales_return_items_invoice_item_id_sales_invoice_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_return_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replacement_product_id'], ['products.id'], name=op.f('fk_sales_return_items_replacement_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replacement_serial_number_id'], ['product_serial_numbers.id'], name=op.f('fk_sales_return_items_replacement_serial_number_id_product_serial_numbers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replacement_stock_movement_id'], ['stock_movements.id'], name=op.f('fk_sales_return_items_replacement_stock_movement_id_stock_movements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], name=op.f('fk_sales_return_items_return_id_sales_returns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serial_number_id'], ['product_serial_numbers.id'], name=op.f('fk_sales_return_items_serial_number_id_product_serial_numbers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], name=op.f('fk_sales_return_items_stock_movement_id_stock_movements'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_return_items'))
    )
    with op.batch_alter_table('sales_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_return_items_condition'), ['condition'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_destination_warehouse_id'), ['destination_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_invoice_item_id'), ['invoice_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_replacement_product_id'), ['replacement_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_replacement_serial_number_id'), ['replacement_serial_number_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_replacement_stock_movement_id'), ['replacement_stock_movement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_return_id'), ['return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_serial_number_id'), ['serial_number_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_stock_movement_id'), ['stock_movement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_return_items_stock_movement_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_serial_number_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_return_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_replacement_stock_movement_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_replacement_serial_number_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_replacement_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_invoice_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_destination_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_condition'))

    op.drop_table('sales_return_items')
    with op.batch_alter_table('sales_return_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_return_status_history_return_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_status_history_new_status'))
        batch_op.drop_index(batch_op.f('ix_sales_return_status_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_return_status_history_changed_by_id'))

    op.drop_table('sales_return_status_history')
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_returns_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_status'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_return_type'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_return_number'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_resolution'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_completed_at'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_company_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_branch_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_approved_by_id'))

    op.drop_table('sales_returns')
    # ### end Alembic commands ###
