"""track invoice credit note amounts

Revision ID: 229a76d1de27
Revises: 3a5c264ce8cb
Create Date: 2026-08-09 17:42:31.432356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229a76d1de27'
down_revision: Union[str, Sequence[str], None] = '3a5c264ce8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credited_amount', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_column('credited_amount')

    # ### end Alembic commands ###
