"""add credit notes and customer refunds

Revision ID: 3a5c264ce8cb
Revises: 1d0d92e814a8
Create Date: 2026-08-09 17:36:35.522773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5c264ce8cb'
down_revision: Union[str, Sequence[str], None] = '1d0d92e814a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('credit_note_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_credit_notes_ck_credit_notes_amount_positive')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_credit_notes_approved_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_credit_notes_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_credit_notes_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_credit_notes_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_credit_notes_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], name=op.f('fk_credit_notes_invoice_id_sales_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], name=op.f('fk_credit_notes_posted_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], name=op.f('fk_credit_notes_return_id_sales_returns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], name=op.f('fk_credit_notes_reversed_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_notes')),
    sa.UniqueConstraint('company_id', 'credit_note_number', name='uq_credit_notes_company_credit_note_number'),
    sa.UniqueConstraint('return_id', name='uq_credit_notes_return_id')
    )
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_notes_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_credit_note_number'), ['credit_note_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_is_reversed'), ['is_reversed'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_posted_by_id'), ['posted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_return_id'), ['return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_reversed_by_id'), ['reversed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_status'), ['status'], unique=False)

    op.create_table('customer_refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('refund_number', sa.String(length=50), nullable=True),
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('refund_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('reference_number', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_customer_refunds_ck_customer_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_customer_refunds_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_refunds_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customer_refunds_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], name=op.f('fk_customer_refunds_credit_note_id_credit_notes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_refunds_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], name=op.f('fk_customer_refunds_invoice_id_sales_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], name=op.f('fk_customer_refunds_posted_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], name=op.f('fk_customer_refunds_return_id_sales_returns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], name=op.f('fk_customer_refunds_reversed_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_refunds')),
    sa.UniqueConstraint('company_id', 'refund_number', name='uq_customer_refunds_company_refund_number')
    )
    with op.batch_alter_table('customer_refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_refunds_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_credit_note_id'), ['credit_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_is_reversed'), ['is_reversed'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_posted_by_id'), ['posted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_refund_method'), ['refund_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_refund_number'), ['refund_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_return_id'), ['return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_reversed_by_id'), ['reversed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_refunds_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_refunds_status'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_reversed_by_id'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_return_id'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_refund_number'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_refund_method'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_posted_by_id'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_is_reversed'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_credit_note_id'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_company_id'))
        batch_op.drop_index(batch_op.f('ix_customer_refunds_branch_id'))

    op.drop_table('customer_refunds')
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_status'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_reversed_by_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_return_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_posted_by_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_is_reversed'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_customer_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_credit_note_number'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_company_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_branch_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_approved_by_id'))

    op.drop_table('credit_notes')
    # ### end Alembic commands ###
