"""add installment plans customer ledger

Revision ID: 3bf2590550f8
Revises: ea5bafe19a52
Create Date: 2026-08-12 08:28:28.394997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf2590550f8'
down_revision: Union[str, Sequence[str], None] = 'ea5bafe19a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('agreement_number', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(length=30), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('financed_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('scheduled_installment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grace_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('financed_amount > 0', name=op.f('ck_installment_plans_ck_installment_plans_financed_positive')),
    sa.CheckConstraint('installment_count > 0', name=op.f('ck_installment_plans_ck_installment_plans_count_positive')),
    sa.CheckConstraint('outstanding_amount >= 0', name=op.f('ck_installment_plans_ck_installment_plans_outstanding_nonnegative')),
    sa.CheckConstraint('total_paid >= 0', name=op.f('ck_installment_plans_ck_installment_plans_paid_nonnegative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_installment_plans_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_installment_plans_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_installment_plans_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_installment_plans_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], name=op.f('fk_installment_plans_invoice_id_sales_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_plans')),
    sa.UniqueConstraint('company_id', 'agreement_number', name='uq_installment_plans_company_agreement'),
    sa.UniqueConstraint('invoice_id', name='uq_installment_plans_invoice')
    )
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installment_plans_agreement_number'), ['agreement_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_plans_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_plans_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_plans_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_plans_first_due_date'), ['first_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_plans_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_plans_status'), ['status'], unique=False)

    op.create_table('installment_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_due > 0', name=op.f('ck_installment_schedules_ck_installment_schedule_due_positive')),
    sa.CheckConstraint('amount_paid >= 0', name=op.f('ck_installment_schedules_ck_installment_schedule_paid_nonnegative')),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], name=op.f('fk_installment_schedules_plan_id_installment_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_schedules')),
    sa.UniqueConstraint('plan_id', 'installment_number', name='uq_installment_schedule_plan_number')
    )
    with op.batch_alter_table('installment_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installment_schedules_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_schedules_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_schedules_status'), ['status'], unique=False)

    op.create_table('installment_payment_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_reversed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_installment_payment_allocations_ck_installment_allocation_amount_positive')),
    sa.ForeignKeyConstraint(['payment_id'], ['customer_payments.id'], name=op.f('fk_installment_payment_allocations_payment_id_customer_payments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], name=op.f('fk_installment_payment_allocations_plan_id_installment_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['installment_schedules.id'], name=op.f('fk_installment_payment_allocations_schedule_id_installment_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_payment_allocations'))
    )
    with op.batch_alter_table('installment_payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installment_payment_allocations_is_reversed'), ['is_reversed'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_payment_allocations_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_payment_allocations_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_payment_allocations_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installment_payment_allocations_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_installment_payment_allocations_plan_id'))
        batch_op.drop_index(batch_op.f('ix_installment_payment_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_installment_payment_allocations_is_reversed'))

    op.drop_table('installment_payment_allocations')
    with op.batch_alter_table('installment_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installment_schedules_status'))
        batch_op.drop_index(batch_op.f('ix_installment_schedules_plan_id'))
        batch_op.drop_index(batch_op.f('ix_installment_schedules_due_date'))

    op.drop_table('installment_schedules')
    with op.batch_alter_table('installment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installment_plans_status'))
        batch_op.drop_index(batch_op.f('ix_installment_plans_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_installment_plans_first_due_date'))
        batch_op.drop_index(batch_op.f('ix_installment_plans_customer_id'))
        batch_op.drop_index(batch_op.f('ix_installment_plans_company_id'))
        batch_op.drop_index(batch_op.f('ix_installment_plans_branch_id'))
        batch_op.drop_index(batch_op.f('ix_installment_plans_agreement_number'))

    op.drop_table('installment_plans')
    # ### end Alembic commands ###
