"""add goods receipts phase2

Revision ID: 4dc4a4f86688
Revises: 852525346297
Create Date: 2026-08-12 00:31:11.231339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc4a4f86688'
down_revision: Union[str, Sequence[str], None] = '852525346297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('grn_number', sa.String(length=40), nullable=True),
    sa.Column('delivery_note_number', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_goods_receipts_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_goods_receipts_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_goods_receipts_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], name=op.f('fk_goods_receipts_received_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_goods_receipts_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_goods_receipts_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipts')),
    sa.UniqueConstraint('company_id', 'grn_number', name='uq_goods_receipts_company_grn_number')
    )
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_delivery_note_number'), ['delivery_note_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_grn_number'), ['grn_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_received_by_id'), ['received_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('goods_receipt_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name=op.f('fk_goods_receipt_items_goods_receipt_id_goods_receipts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_goods_receipt_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], name=op.f('fk_goods_receipt_items_purchase_order_item_id_purchase_order_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_items'))
    )
    with op.batch_alter_table('goods_receipt_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_items_goods_receipt_id'), ['goods_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_items_purchase_order_item_id'), ['purchase_order_item_id'], unique=False)

    op.create_table('goods_receipt_serials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods_receipt_item_id', sa.Integer(), nullable=False),
    sa.Column('product_serial_number_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=150), nullable=False),
    sa.Column('secondary_serial_number', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['goods_receipt_item_id'], ['goods_receipt_items.id'], name=op.f('fk_goods_receipt_serials_goods_receipt_item_id_goods_receipt_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_serial_number_id'], ['product_serial_numbers.id'], name=op.f('fk_goods_receipt_serials_product_serial_number_id_product_serial_numbers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_serials')),
    sa.UniqueConstraint('product_serial_number_id', name='uq_goods_receipt_serials_product_serial')
    )
    with op.batch_alter_table('goods_receipt_serials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_serials_goods_receipt_item_id'), ['goods_receipt_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_serials_product_serial_number_id'), ['product_serial_number_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods_receipt_serials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_serials_product_serial_number_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_serials_goods_receipt_item_id'))

    op.drop_table('goods_receipt_serials')
    with op.batch_alter_table('goods_receipt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_items_purchase_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_items_goods_receipt_id'))

    op.drop_table('goods_receipt_items')
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipts_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_received_by_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_grn_number'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_delivery_note_number'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_company_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_branch_id'))

    op.drop_table('goods_receipts')
    # ### end Alembic commands ###
