"""add suppliers table

Revision ID: 4ee03aa57aac
Revises: cee6a914590a
Create Date: 2026-08-06 09:25:52.094665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee03aa57aac'
down_revision: Union[str, Sequence[str], None] = 'cee6a914590a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=30), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('current_payable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_suppliers_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_suppliers_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_suppliers_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('company_id', 'company_name', name='uq_suppliers_company_company_name'),
    sa.UniqueConstraint('company_id', 'email', name='uq_suppliers_company_email'),
    sa.UniqueConstraint('company_id', 'phone', name='uq_suppliers_company_phone'),
    sa.UniqueConstraint('company_id', 'supplier_code', name='uq_suppliers_company_supplier_code')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_supplier_code'), ['supplier_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_updated_by_id'), ['updated_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_suppliers_phone'))
        batch_op.drop_index(batch_op.f('ix_suppliers_is_active'))
        batch_op.drop_index(batch_op.f('ix_suppliers_email'))
        batch_op.drop_index(batch_op.f('ix_suppliers_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_company_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_company_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_city'))

    op.drop_table('suppliers')
    # ### end Alembic commands ###
