"""add purchase orders phase1

Revision ID: 852525346297
Revises: 23def43d30ef
Create Date: 2026-08-11 23:41:11.504152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852525346297'
down_revision: Union[str, Sequence[str], None] = '23def43d30ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=250), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_purchase_orders_approved_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_purchase_orders_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name=op.f('fk_purchase_orders_cancelled_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_purchase_orders_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_purchase_orders_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_purchase_orders_updated_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_purchase_orders_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('company_id', 'purchase_order_number', name='uq_purchase_orders_company_number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_cancelled_by_id'), ['cancelled_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_expected_date'), ['expected_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_purchase_order_number'), ['purchase_order_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_updated_by_id'), ['updated_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_items_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items')),
    sa.UniqueConstraint('purchase_order_id', 'product_id', name='uq_purchase_order_items_order_product')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_product_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_purchase_order_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_order_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_expected_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_company_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_cancelled_by_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_branch_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_approved_by_id'))

    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
