"""support legacy debt installment plans

Revision ID: 877748e87094
Revises: 75e5e5130acb
Create Date: 2026-09-01 08:29:28.748422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877748e87094'
down_revision: Union[str, Sequence[str], None] = '75e5e5130acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_plans', sa.Column('source_type', sa.String(length=30), server_default='sales_invoice', nullable=False))
    op.add_column('installment_plans', sa.Column('legacy_principal_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.alter_column('installment_plans', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_installment_plans_source_type'), 'installment_plans', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installment_plans_source_type'), table_name='installment_plans')
    op.alter_column('installment_plans', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('installment_plans', 'legacy_principal_amount')
    op.drop_column('installment_plans', 'source_type')
    # ### end Alembic commands ###
