"""create service center tables

Revision ID: a651a5df4da9
Revises: 926f815380fd
Create Date: 2026-08-09 10:48:19.359001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a651a5df4da9'
down_revision: Union[str, Sequence[str], None] = '926f815380fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_job_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sold_serial_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('secondary_serial_number', sa.String(length=150), nullable=True),
    sa.Column('brand_name', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('item_color', sa.String(length=80), nullable=True),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('reported_issue', sa.Text(), nullable=True),
    sa.Column('technician_diagnosis', sa.Text(), nullable=True),
    sa.Column('work_performed', sa.Text(), nullable=True),
    sa.Column('testing_result', sa.Text(), nullable=True),
    sa.Column('accessories_received', sa.Text(), nullable=True),
    sa.Column('physical_condition', sa.Text(), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('receiving_officer_id', sa.Integer(), nullable=True),
    sa.Column('is_warranty_job', sa.Boolean(), nullable=False),
    sa.Column('warranty_verified', sa.Boolean(), nullable=False),
    sa.Column('warranty_notes', sa.Text(), nullable=True),
    sa.Column('related_invoice_id', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('labour_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('parts_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('approval_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_service_job_cards_discount_amount_nonnegative')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_service_job_cards_estimated_cost_nonnegative')),
    sa.CheckConstraint('final_amount >= 0', name=op.f('ck_service_job_cards_final_amount_nonnegative')),
    sa.CheckConstraint('labour_total >= 0', name=op.f('ck_service_job_cards_labour_total_nonnegative')),
    sa.CheckConstraint('parts_total >= 0', name=op.f('ck_service_job_cards_parts_total_nonnegative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_service_job_cards_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_service_job_cards_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_service_job_cards_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_service_job_cards_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_service_job_cards_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiving_officer_id'], ['users.id'], name=op.f('fk_service_job_cards_receiving_officer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['sales_invoices.id'], name=op.f('fk_service_job_cards_related_invoice_id_sales_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sold_serial_id'], ['product_serial_numbers.id'], name=op.f('fk_service_job_cards_sold_serial_id_product_serial_numbers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('fk_service_job_cards_technician_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_service_job_cards_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_job_cards')),
    sa.UniqueConstraint('company_id', 'job_number', name='uq_service_job_cards_company_job_number')
    )
    with op.batch_alter_table('service_job_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_job_cards_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_expected_completion_date'), ['expected_completion_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_is_warranty_job'), ['is_warranty_job'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_job_number'), ['job_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_receiving_officer_id'), ['receiving_officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_related_invoice_id'), ['related_invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_secondary_serial_number'), ['secondary_serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_sold_serial_id'), ['sold_serial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_technician_id'), ['technician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_cards_updated_by_id'), ['updated_by_id'], unique=False)

    op.create_table('service_checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=250), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], name=op.f('fk_service_checklist_items_completed_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_card_id'], ['service_job_cards.id'], name=op.f('fk_service_checklist_items_job_card_id_service_job_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_checklist_items'))
    )
    with op.batch_alter_table('service_checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_checklist_items_completed_by_id'), ['completed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_checklist_items_is_completed'), ['is_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_checklist_items_job_card_id'), ['job_card_id'], unique=False)

    op.create_table('service_job_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['service_job_cards.id'], name=op.f('fk_service_job_images_job_card_id_service_job_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_service_job_images_uploaded_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_job_images'))
    )
    with op.batch_alter_table('service_job_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_job_images_image_type'), ['image_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_images_job_card_id'), ['job_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_images_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    op.create_table('service_job_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stock_movement_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_service_job_parts_line_total_nonnegative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_service_job_parts_quantity_positive')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_service_job_parts_unit_cost_nonnegative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_service_job_parts_unit_price_nonnegative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_service_job_parts_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_card_id'], ['service_job_cards.id'], name=op.f('fk_service_job_parts_job_card_id_service_job_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_service_job_parts_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], name=op.f('fk_service_job_parts_stock_movement_id_stock_movements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_service_job_parts_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_job_parts'))
    )
    with op.batch_alter_table('service_job_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_job_parts_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_parts_job_card_id'), ['job_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_parts_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_parts_stock_movement_id'), ['stock_movement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_parts_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('service_job_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_service_job_status_history_changed_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_card_id'], ['service_job_cards.id'], name=op.f('fk_service_job_status_history_job_card_id_service_job_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_job_status_history'))
    )
    with op.batch_alter_table('service_job_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_job_status_history_changed_by_id'), ['changed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_status_history_job_card_id'), ['job_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_job_status_history_new_status'), ['new_status'], unique=False)

    op.create_table('service_labour_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_service_labour_items_amount_nonnegative')),
    sa.CheckConstraint('hours >= 0', name=op.f('ck_service_labour_items_hours_nonnegative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_service_labour_items_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_card_id'], ['service_job_cards.id'], name=op.f('fk_service_labour_items_job_card_id_service_job_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_labour_items'))
    )
    with op.batch_alter_table('service_labour_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_labour_items_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_labour_items_job_card_id'), ['job_card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_labour_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_labour_items_job_card_id'))
        batch_op.drop_index(batch_op.f('ix_service_labour_items_created_by_id'))

    op.drop_table('service_labour_items')
    with op.batch_alter_table('service_job_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_job_status_history_new_status'))
        batch_op.drop_index(batch_op.f('ix_service_job_status_history_job_card_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_status_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_service_job_status_history_changed_by_id'))

    op.drop_table('service_job_status_history')
    with op.batch_alter_table('service_job_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_job_parts_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_parts_stock_movement_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_parts_product_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_parts_job_card_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_parts_created_by_id'))

    op.drop_table('service_job_parts')
    with op.batch_alter_table('service_job_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_job_images_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_images_job_card_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_images_image_type'))

    op.drop_table('service_job_images')
    with op.batch_alter_table('service_checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_checklist_items_job_card_id'))
        batch_op.drop_index(batch_op.f('ix_service_checklist_items_is_completed'))
        batch_op.drop_index(batch_op.f('ix_service_checklist_items_completed_by_id'))

    op.drop_table('service_checklist_items')
    with op.batch_alter_table('service_job_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_job_cards_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_technician_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_status'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_sold_serial_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_service_type'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_serial_number'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_secondary_serial_number'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_related_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_receiving_officer_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_received_at'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_product_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_priority'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_job_number'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_is_warranty_job'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_expected_completion_date'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_customer_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_completed_at'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_company_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_branch_id'))
        batch_op.drop_index(batch_op.f('ix_service_job_cards_approval_status'))

    op.drop_table('service_job_cards')
    # ### end Alembic commands ###
