"""add manual cash book entries

Revision ID: af54a247c8ed
Revises: d4e8c2a91f7b
Create Date: 2026-08-26 08:29:43.215351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af54a247c8ed'
down_revision: Union[str, Sequence[str], None] = 'd4e8c2a91f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_cash_book_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=50), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), server_default='cash', nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.Column('reversal_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('cash_in', 'cash_out')", name=op.f('ck_manual_cash_book_entries_ck_manual_cash_book_entries_entry_type')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_manual_cash_book_entries_ck_manual_cash_book_entries_amount_positive')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_manual_cash_book_entries_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_manual_cash_book_entries_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_manual_cash_book_entries_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], name=op.f('fk_manual_cash_book_entries_reversed_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_cash_book_entries'))
    )
    op.create_index('ix_manual_cash_book_entries_branch_entry_date', 'manual_cash_book_entries', ['branch_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_branch_id'), 'manual_cash_book_entries', ['branch_id'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_category'), 'manual_cash_book_entries', ['category'], unique=False)
    op.create_index('ix_manual_cash_book_entries_company_entry_date', 'manual_cash_book_entries', ['company_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_company_id'), 'manual_cash_book_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_created_by_id'), 'manual_cash_book_entries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_entry_date'), 'manual_cash_book_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_entry_number'), 'manual_cash_book_entries', ['entry_number'], unique=True)
    op.create_index(op.f('ix_manual_cash_book_entries_entry_type'), 'manual_cash_book_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_payment_method'), 'manual_cash_book_entries', ['payment_method'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_reference_number'), 'manual_cash_book_entries', ['reference_number'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_reversed_at'), 'manual_cash_book_entries', ['reversed_at'], unique=False)
    op.create_index(op.f('ix_manual_cash_book_entries_reversed_by_id'), 'manual_cash_book_entries', ['reversed_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_cash_book_entries_reversed_by_id'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_reversed_at'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_reference_number'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_payment_method'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_entry_type'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_entry_number'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_entry_date'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_created_by_id'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_company_id'), table_name='manual_cash_book_entries')
    op.drop_index('ix_manual_cash_book_entries_company_entry_date', table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_category'), table_name='manual_cash_book_entries')
    op.drop_index(op.f('ix_manual_cash_book_entries_branch_id'), table_name='manual_cash_book_entries')
    op.drop_index('ix_manual_cash_book_entries_branch_entry_date', table_name='manual_cash_book_entries')
    op.drop_table('manual_cash_book_entries')
    # ### end Alembic commands ###
