"""add sales invoices items and customer payments

Revision ID: c6f6ba44de6f
Revises: 00508f14101d
Create Date: 2026-08-07 08:48:02.809951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f6ba44de6f'
down_revision: Union[str, Sequence[str], None] = '00508f14101d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('invoice_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('balance_amount >= 0', name=op.f('ck_sales_invoices_ck_sales_invoices_balance_nonnegative')),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_sales_invoices_ck_sales_invoices_discount_nonnegative')),
    sa.CheckConstraint('grand_total >= 0', name=op.f('ck_sales_invoices_ck_sales_invoices_grand_total_nonnegative')),
    sa.CheckConstraint('paid_amount >= 0', name=op.f('ck_sales_invoices_ck_sales_invoices_paid_nonnegative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_sales_invoices_ck_sales_invoices_subtotal_nonnegative')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_sales_invoices_ck_sales_invoices_tax_nonnegative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_sales_invoices_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sales_invoices_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sales_invoices_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_invoices_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_sales_invoices_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_invoices')),
    sa.UniqueConstraint('company_id', 'invoice_number', name='uq_sales_invoices_company_invoice_number')
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoices_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_invoice_date'), ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_invoice_status'), ['invoice_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_updated_by_id'), ['updated_by_id'], unique=False)

    op.create_table('customer_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('reference_number', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_customer_payments_ck_customer_payments_amount_positive')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_customer_payments_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_payments_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customer_payments_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_payments_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], name=op.f('fk_customer_payments_invoice_id_sales_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_payments')),
    sa.UniqueConstraint('company_id', 'receipt_number', name='uq_customer_payments_company_receipt_number')
    )
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_payments_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_is_reversed'), ['is_reversed'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_receipt_number'), ['receipt_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_reference_number'), ['reference_number'], unique=False)

    op.create_table('sales_invoice_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serial_number_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_sales_invoice_items_ck_sales_invoice_items_discount_nonnegative')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_sales_invoice_items_ck_sales_invoice_items_line_total_nonnegative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sales_invoice_items_ck_sales_invoice_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_sales_invoice_items_ck_sales_invoice_items_unit_price_nonnegative')),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], name=op.f('fk_sales_invoice_items_invoice_id_sales_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_invoice_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['serial_number_id'], ['product_serial_numbers.id'], name=op.f('fk_sales_invoice_items_serial_number_id_product_serial_numbers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_invoice_items'))
    )
    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_serial_number_id'), ['serial_number_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_serial_number_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_invoice_id'))

    op.drop_table('sales_invoice_items')
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_payments_reference_number'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_payment_method'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_is_reversed'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_company_id'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_branch_id'))

    op.drop_table('customer_payments')
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoices_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_payment_status'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_invoice_date'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_company_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_branch_id'))

    op.drop_table('sales_invoices')
    # ### end Alembic commands ###
