"""add customers table

Revision ID: cee6a914590a
Revises: b5bef7aaba48
Create Date: 2026-08-06 09:16:13.021453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee6a914590a'
down_revision: Union[str, Sequence[str], None] = 'b5bef7aaba48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=30), nullable=True),
    sa.Column('customer_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('nic_number', sa.String(length=20), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('sms_phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('credit_status', sa.String(length=30), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sms_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customers_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customers_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_customers_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('company_id', 'customer_number', name='uq_customers_company_customer_number'),
    sa.UniqueConstraint('company_id', 'email', name='uq_customers_company_email'),
    sa.UniqueConstraint('company_id', 'nic_number', name='uq_customers_company_nic_number'),
    sa.UniqueConstraint('company_id', 'primary_phone', name='uq_customers_company_primary_phone')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_business_name'), ['business_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_customer_number'), ['customer_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_customer_type'), ['customer_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_nic_number'), ['nic_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_primary_phone'), ['primary_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_updated_by_id'), ['updated_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_customers_status'))
        batch_op.drop_index(batch_op.f('ix_customers_primary_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_nic_number'))
        batch_op.drop_index(batch_op.f('ix_customers_full_name'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_type'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_number'))
        batch_op.drop_index(batch_op.f('ix_customers_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_customers_company_id'))
        batch_op.drop_index(batch_op.f('ix_customers_city'))
        batch_op.drop_index(batch_op.f('ix_customers_business_name'))

    op.drop_table('customers')
    # ### end Alembic commands ###
