"""add supplier invoices payments phase3

Revision ID: ea5bafe19a52
Revises: 4dc4a4f86688
Create Date: 2026-08-12 01:31:48.436742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5bafe19a52'
down_revision: Union[str, Sequence[str], None] = '4dc4a4f86688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('supplier_invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_supplier_invoices_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_supplier_invoices_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_supplier_invoices_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name=op.f('fk_supplier_invoices_goods_receipt_id_goods_receipts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], name=op.f('fk_supplier_invoices_posted_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_supplier_invoices_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], name=op.f('fk_supplier_invoices_reversed_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_invoices_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_invoices')),
    sa.UniqueConstraint('company_id', 'invoice_number', name='uq_supplier_invoices_company_invoice_number'),
    sa.UniqueConstraint('company_id', 'supplier_id', 'supplier_invoice_number', name='uq_supplier_invoices_supplier_reference')
    )
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_invoices_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_goods_receipt_id'), ['goods_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_supplier_invoice_number'), ['supplier_invoice_number'], unique=False)

    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_number', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('reference_number', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_supplier_payments_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_supplier_payments_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_supplier_payments_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], name=op.f('fk_supplier_payments_reversed_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_payments_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], name=op.f('fk_supplier_payments_supplier_invoice_id_supplier_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_payments')),
    sa.UniqueConstraint('company_id', 'payment_number', name='uq_supplier_payments_company_payment_number')
    )
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_payments_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_payments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_payments_payment_number'), ['payment_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_payments_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_payments_supplier_invoice_id'), ['supplier_invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_payments_supplier_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_payments_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_payments_payment_number'))
        batch_op.drop_index(batch_op.f('ix_supplier_payments_company_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_payments_branch_id'))

    op.drop_table('supplier_payments')
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_supplier_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_goods_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_company_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_branch_id'))

    op.drop_table('supplier_invoices')
    # ### end Alembic commands ###
