"""support service job invoices

Revision ID: eeb19d52c939
Revises: a651a5df4da9
Create Date: 2026-08-09 11:42:01.691673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb19d52c939'
down_revision: Union[str, Sequence[str], None] = 'a651a5df4da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=30), server_default='product', nullable=False))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_sales_invoice_items_item_type'), ['item_type'], unique=False)

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=30), server_default='sales', nullable=False))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_invoices_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_source_type'), ['source_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoices_source_type'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_source_id'))
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('sales_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_items_item_type'))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###
