"""add sales invoice due date

Revision ID: fafbb34f4271
Revises: c903ca453bac
Create Date: 2026-08-20 22:28:54.321818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafbb34f4271'
down_revision: Union[str, Sequence[str], None] = 'c903ca453bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_sales_invoices_due_date'), 'sales_invoices', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_invoices_due_date'), table_name='sales_invoices')
    op.drop_column('sales_invoices', 'due_date')
    # ### end Alembic commands ###
